version: '3'

services:
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    restart: always
    privileged: true
    ports:
      - 21194:1194/udp
    cap_add:
      - NET_ADMIN
    volumes:
      - ./conf:/etc/openvpn
